//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Read_and_learn.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Read_and_learn.AppResources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image assets original site: https://www.flaticon.com/.
        /// </summary>
        internal static string AboutPage_ImageAssetsLabel {
            get {
                return ResourceManager.GetString("AboutPage_ImageAssetsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful links:.
        /// </summary>
        internal static string AboutPage_UsefulLinksLabel {
            get {
                return ResourceManager.GetString("AboutPage_UsefulLinksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string AddBookCard_AddButtonLabel {
            get {
                return ResourceManager.GetString("AddBookCard_AddButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press once again to exit!.
        /// </summary>
        internal static string App_ClickForExit {
            get {
                return ResourceManager.GetString("App_ClickForExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with collecting of anonymous information about using of the app. This is important for application improvements..
        /// </summary>
        internal static string ApplicationSettings_AnonymousData_FirstPart {
            get {
                return ResourceManager.GetString("ApplicationSettings_AnonymousData_FirstPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can be collected: that some book failed to open and name of the file. Problems with translation service(s)..
        /// </summary>
        internal static string ApplicationSettings_AnonymousData_SecondPart {
            get {
                return ResourceManager.GetString("ApplicationSettings_AnonymousData_SecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous data.
        /// </summary>
        internal static string ApplicationSettings_AnonymousDataLabel {
            get {
                return ResourceManager.GetString("ApplicationSettings_AnonymousDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language used to localize the application..
        /// </summary>
        internal static string ApplicationSettings_ApplicationLanguage_HintLabel {
            get {
                return ResourceManager.GetString("ApplicationSettings_ApplicationLanguage_HintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application language.
        /// </summary>
        internal static string ApplicationSettings_ApplicationLanguageLabel {
            get {
                return ResourceManager.GetString("ApplicationSettings_ApplicationLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select system language.
        /// </summary>
        internal static string ApplicationSettings_ApplicationLanguageLabel_Picker_Title {
            get {
                return ResourceManager.GetString("ApplicationSettings_ApplicationLanguageLabel_Picker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string ApplicationSettings_Title {
            get {
                return ResourceManager.GetString("ApplicationSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan on the edge of display for brightness control..
        /// </summary>
        internal static string ControlSettings_Brightness_HintTitle {
            get {
                return ResourceManager.GetString("ControlSettings_Brightness_HintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set brightness control.
        /// </summary>
        internal static string ControlSettings_Brightness_PickerTitle {
            get {
                return ResourceManager.GetString("ControlSettings_Brightness_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change brightness.
        /// </summary>
        internal static string ControlSettings_BrightnessTitle {
            get {
                return ResourceManager.GetString("ControlSettings_BrightnessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string ControlSettings_Title {
            get {
                return ResourceManager.GetString("ControlSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use volume buttons for navigation..
        /// </summary>
        internal static string ControlSettings_VolumeButtons_HintTitle {
            get {
                return ResourceManager.GetString("ControlSettings_VolumeButtons_HintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume buttons.
        /// </summary>
        internal static string ControlSettings_VolumeButtonsTitle {
            get {
                return ResourceManager.GetString("ControlSettings_VolumeButtonsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string HomePage_About {
            get {
                return ResourceManager.GetString("HomePage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        internal static string HomePage_AnalyticsAgreement_Accept {
            get {
                return ResourceManager.GetString("HomePage_AnalyticsAgreement_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string HomePage_AnalyticsAgreement_Cancel {
            get {
                return ResourceManager.GetString("HomePage_AnalyticsAgreement_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with collecting of anonymous information about using of the app. This is important for application improvements..
        /// </summary>
        internal static string HomePage_AnalyticsAgreement_Message {
            get {
                return ResourceManager.GetString("HomePage_AnalyticsAgreement_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement with collection of anonymous data.
        /// </summary>
        internal static string HomePage_AnalyticsAgreement_Title {
            get {
                return ResourceManager.GetString("HomePage_AnalyticsAgreement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string HomePage_Delete_Button {
            get {
                return ResourceManager.GetString("HomePage_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete book?.
        /// </summary>
        internal static string HomePage_Delete_Title {
            get {
                return ResourceManager.GetString("HomePage_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string HomePage_Error_Cancel {
            get {
                return ResourceManager.GetString("HomePage_Error_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File failed to open.
        /// </summary>
        internal static string HomePage_Error_Message {
            get {
                return ResourceManager.GetString("HomePage_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string HomePage_Error_Title {
            get {
                return ResourceManager.GetString("HomePage_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string HomePage_Permission_Cancel {
            get {
                return ResourceManager.GetString("HomePage_Permission_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open book without storage permissions.
        /// </summary>
        internal static string HomePage_Permission_Message {
            get {
                return ResourceManager.GetString("HomePage_Permission_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission not granted.
        /// </summary>
        internal static string HomePage_Permission_Title {
            get {
                return ResourceManager.GetString("HomePage_Permission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string HomePage_Settings {
            get {
                return ResourceManager.GetString("HomePage_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My books.
        /// </summary>
        internal static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MasterFlyoutPageDetail_AboutPageTitle {
            get {
                return ResourceManager.GetString("MasterFlyoutPageDetail_AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My books.
        /// </summary>
        internal static string MasterFlyoutPageDetail_HomePageTitle {
            get {
                return ResourceManager.GetString("MasterFlyoutPageDetail_HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MasterFlyoutPageDetail_SettingsPageTitle {
            get {
                return ResourceManager.GetString("MasterFlyoutPageDetail_SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bookmark.
        /// </summary>
        internal static string ReaderMenu_Bookmark_AddBookmarckTitle {
            get {
                return ResourceManager.GetString("ReaderMenu_Bookmark_AddBookmarckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        internal static string ReaderMenu_Settings_BrightnessTitle {
            get {
                return ResourceManager.GetString("ReaderMenu_Settings_BrightnessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string ReaderMenu_Settings_FontSize_PickerTitle {
            get {
                return ResourceManager.GetString("ReaderMenu_Settings_FontSize_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string ReaderMenu_Settings_FontSizeTitle {
            get {
                return ResourceManager.GetString("ReaderMenu_Settings_FontSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string ReaderMenu_Settings_Margin_PickerTitle {
            get {
                return ResourceManager.GetString("ReaderMenu_Settings_Margin_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string ReaderMenu_Settings_MarginTitle {
            get {
                return ResourceManager.GetString("ReaderMenu_Settings_MarginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        internal static string ReaderMenuPanel_BookmarksTitle {
            get {
                return ResourceManager.GetString("ReaderMenuPanel_BookmarksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string ReaderMenuPanel_ContentTitle {
            get {
                return ResourceManager.GetString("ReaderMenuPanel_ContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can`t translate part of text without Internet connection..
        /// </summary>
        internal static string ReaderPage_NoInternet {
            get {
                return ResourceManager.GetString("ReaderPage_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have finished reading this book!.
        /// </summary>
        internal static string ReaderPage_ReadingFinished {
            get {
                return ResourceManager.GetString("ReaderPage_ReadingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose second word!.
        /// </summary>
        internal static string ReaderPage_SecondWord {
            get {
                return ResourceManager.GetString("ReaderPage_SecondWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during translation. Please contact the developer.\r\nException message:.
        /// </summary>
        internal static string ReaderPage_Translation_Error {
            get {
                return ResourceManager.GetString("ReaderPage_Translation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider:.
        /// </summary>
        internal static string ReaderPage_Translation_Provider {
            get {
                return ResourceManager.GetString("ReaderPage_Translation_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        internal static string ReaderPage_Translation_Result {
            get {
                return ResourceManager.GetString("ReaderPage_Translation_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonyms:.
        /// </summary>
        internal static string ReaderPage_Translation_Synonyms {
            get {
                return ResourceManager.GetString("ReaderPage_Translation_Synonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples of usage:.
        /// </summary>
        internal static string ReaderPage_Translation_Usages {
            get {
                return ResourceManager.GetString("ReaderPage_Translation_Usages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ReaderPage_TranslationResult_Cancle {
            get {
                return ResourceManager.GetString("ReaderPage_TranslationResult_Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation result:.
        /// </summary>
        internal static string ReaderPage_TranslationResult_Title {
            get {
                return ResourceManager.GetString("ReaderPage_TranslationResult_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select font size.
        /// </summary>
        internal static string ReaderSettings_FontSize_HintLabel {
            get {
                return ResourceManager.GetString("ReaderSettings_FontSize_HintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string ReaderSettings_FontSizeLabel {
            get {
                return ResourceManager.GetString("ReaderSettings_FontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open book in fullscreen mode..
        /// </summary>
        internal static string ReaderSettings_Fullscreen_HintLabel {
            get {
                return ResourceManager.GetString("ReaderSettings_Fullscreen_HintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string ReaderSettings_FullscreenLabel {
            get {
                return ResourceManager.GetString("ReaderSettings_FullscreenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select margin.
        /// </summary>
        internal static string ReaderSettings_Margin_HintLabel {
            get {
                return ResourceManager.GetString("ReaderSettings_Margin_HintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string ReaderSettings_MarginLabel {
            get {
                return ResourceManager.GetString("ReaderSettings_MarginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use night mode when reading..
        /// </summary>
        internal static string ReaderSettings_NightMode_HintLabel {
            get {
                return ResourceManager.GetString("ReaderSettings_NightMode_HintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night mode.
        /// </summary>
        internal static string ReaderSettings_NightModeLabel {
            get {
                return ResourceManager.GetString("ReaderSettings_NightModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        internal static string ReaderSettings_Title {
            get {
                return ResourceManager.GetString("ReaderSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no available translation for target word :(.
        /// </summary>
        internal static string Translation_NoAvailableTranlsation {
            get {
                return ResourceManager.GetString("Translation_NoAvailableTranlsation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string Translation_NoInternetConnection {
            get {
                return ResourceManager.GetString("Translation_NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source language not supported for translation..
        /// </summary>
        internal static string Translation_SourceLanguageNotSupported {
            get {
                return ResourceManager.GetString("Translation_SourceLanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target language not supported by current provider! Supported languages:.
        /// </summary>
        internal static string Translation_TargetLanguageNotSupported {
            get {
                return ResourceManager.GetString("Translation_TargetLanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can`t use target provider due to internet settings (blocked in the Ukraine)..
        /// </summary>
        internal static string Translation_Yandex_BlockedInCountryError {
            get {
                return ResourceManager.GetString("Translation_Yandex_BlockedInCountryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string TranslationSettings_Title {
            get {
                return ResourceManager.GetString("TranslationSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language into which the translation will be made..
        /// </summary>
        internal static string TranslationSettings_TranslationLanguage_HintTitle {
            get {
                return ResourceManager.GetString("TranslationSettings_TranslationLanguage_HintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select target language for translation.
        /// </summary>
        internal static string TranslationSettings_TranslationLanguage_PickerTitle {
            get {
                return ResourceManager.GetString("TranslationSettings_TranslationLanguage_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected language for translate.
        /// </summary>
        internal static string TranslationSettings_TranslationLanguageTitle {
            get {
                return ResourceManager.GetString("TranslationSettings_TranslationLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider for online translation..
        /// </summary>
        internal static string TranslationSettings_TranslationProvider_HintTitle {
            get {
                return ResourceManager.GetString("TranslationSettings_TranslationProvider_HintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select translation provider.
        /// </summary>
        internal static string TranslationSettings_TranslationProvider_PickerTitle {
            get {
                return ResourceManager.GetString("TranslationSettings_TranslationProvider_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected provider for translate.
        /// </summary>
        internal static string TranslationSettings_TranslationProviderTitle {
            get {
                return ResourceManager.GetString("TranslationSettings_TranslationProviderTitle", resourceCulture);
            }
        }
    }
}
