name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  gated_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Build solution
      run: |
        dotnet restore ./src/
        dotnet build -c Release --no-restore ./src/Read-and-learn/Read-and-learn/Read_and_learn.csproj
    - name: Run tests
      run: |
        dotnet test --no-restore -v m ./src/Read_and_learn.Tests/

  Android:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.0      
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'   
      - name: Build Solution
        run: msbuild ./src/Read-and-learn/ /restore /p:Configuration=Release
      - name: Create and Sign the APK
        run: msbuild ./src/Read-and-learn/Read-and-learn.Android/Read_and_learn.Android.csproj /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Release /p:OutputPath=bin\Release\
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApplication.apk
          path: /src/Read-and-learn/Read-and-learn.Android/bin/Release/danylo.novykov.read_and_learn-Signed.apk 
