name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  gated_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Build solution
      run: |
        dotnet restore ./src/
        dotnet build -c Release --no-restore ./src/Read-and-learn/
    - name: Run tests
      run: |
        dotnet test --no-restore -v m ./src/Read_and_learn.Tests/

  Android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd ./src/
        nuget restore
        cd ./src/Read-and-learn/Read-and-learn.Android/
        msbuild Read_and_learn.Android.csproj /verbosity:normal /t:Rebuild /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Release 
    - uses: actions/upload-artifact@v2
      with:
        name: Android App apk
        path: ./src/Read-and-learn/Read-and-learn.Android/bin/Release/com.tfp.read_and_learn-Signed.apk    
